export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_ALL_DIETS = 'GET_ALL_DIETS';
export const FILTER_BY_DIET_TYPE = 'FILTER_BY_DIET_TYPE';
export const GET_RECIPE_BY_NAME = 'GET_RECIPE_BY_NAME';
export const SORT_ALPHABETICALLY = 'SORT_ALPHABETICALLY';
export const FILTER_BY_SCORE = 'FILTER_BY_SCORE';
export const POST_RECIPE = 'POST_RECIPE';